#!/bin/bash
set -e

chmod +x /opt/edge-plc/irrigacao
chmod +x /opt/edge-plc/irrigacao-atualizador

systemctl daemon-reload

systemctl enable irrigacao.service
systemctl enable irrigacao-atualizador.service

systemctl start irrigacao.service
systemctl start irrigacao-atualizador.service
