// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftwareIrrigacao.Data;

#nullable disable

namespace SoftwareIrrigacao.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SoftwareIrrigacaoContext))]
    [Migration("20260625184847_Atualizacao")]
    partial class Atualizacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SoftwareIrrigacao.Domain.Entity.Configuracao", b =>
                {
                    b.Property<string>("Chave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Chave");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("configuracoes", (string)null);
                });

            modelBuilder.Entity("Toolbox.Automacao.Sincronizacao.Infrastructure.Data.Entity.ControladorConfiguracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Controlador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("controladores_configuracao", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
