<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.7.0" />
    <PackageReference Include="MQTTnet" Version="5.2.0.1603" />
    <PackageReference Include="NModbus" Version="3.0.83" />
    <PackageReference Include="NModbus.Serial" Version="3.0.83" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Toolbox.Core.Api" Version="1.0.0-rc-20260428-1645" />
    <PackageReference Include="System.IO.Ports" Version="10.0.9" />
  </ItemGroup>
</Project>
