<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
    <NeutralLanguage>pt-BR</NeutralLanguage>
    <NoWarn>CS8981,IDE1006</NoWarn>
    <UserSecretsId>9f6b9367-ffcc-4737-bbcd-d4f16e150b14</UserSecretsId>
  </PropertyGroup>

  <!-- RELEASE — Produção -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>linux-arm64</RuntimeIdentifier>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Optimize>true</Optimize>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Remove="Application\**" />
    <Compile Remove="Domain\**" />
    <Compile Remove="Features\Telemetria\Dispositivos\**" />
    <Compile Remove="Features\Telemetria\Simus\**" />
    <Compile Remove="Logs\**" />
    <Content Remove="Application\**" />
    <Content Remove="Domain\**" />
    <Content Remove="Features\Telemetria\Dispositivos\**" />
    <Content Remove="Features\Telemetria\Simus\**" />
    <Content Remove="Logs\**" />
    <EmbeddedResource Remove="Application\**" />
    <EmbeddedResource Remove="Domain\**" />
    <EmbeddedResource Remove="Features\Telemetria\Dispositivos\**" />
    <EmbeddedResource Remove="Features\Telemetria\Simus\**" />
    <EmbeddedResource Remove="Logs\**" />
    <None Remove="Application\**" />
    <None Remove="Domain\**" />
    <None Remove="Features\Telemetria\Dispositivos\**" />
    <None Remove="Features\Telemetria\Simus\**" />
    <None Remove="Logs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Toolbox.Industrial.Core\Toolbox.Industrial.Core.csproj" />
    <ProjectReference Include="..\Toolbox.Industrial.Driver\Toolbox.Industrial.Driver.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>
</Project>
