<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9f6b9367-ffcc-4737-bbcd-d4f16e150b14</UserSecretsId>
  </PropertyGroup>

  <!-- RELEASE — Produção -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>linux-arm64</RuntimeIdentifier>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Optimize>true</Optimize>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Application\**" />
    <Compile Remove="Features\Telemetria\Dispositivos\**" />
    <Compile Remove="Features\Telemetria\Simus\**" />
    <Compile Remove="Logs\**" />
    <Content Remove="Application\**" />
    <Content Remove="Features\Telemetria\Dispositivos\**" />
    <Content Remove="Features\Telemetria\Simus\**" />
    <Content Remove="Logs\**" />
    <EmbeddedResource Remove="Application\**" />
    <EmbeddedResource Remove="Features\Telemetria\Dispositivos\**" />
    <EmbeddedResource Remove="Features\Telemetria\Simus\**" />
    <EmbeddedResource Remove="Logs\**" />
    <None Remove="Application\**" />
    <None Remove="Features\Telemetria\Dispositivos\**" />
    <None Remove="Features\Telemetria\Simus\**" />
    <None Remove="Logs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.7" />
    <PackageReference Include="Toolbox.Core.Api" Version="1.0.0-rc-20260428-1645" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Toolbox.Automacao.Core\Toolbox.Automacao.Core.csproj" />
    <ProjectReference Include="..\Toolbox.Automacao.Irrigacao\Toolbox.Automacao.Irrigacao.csproj" />
    <ProjectReference Include="..\Toolbox.Modulo.Tekon\Toolbox.Modulo.Tekon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Domain\Entity\" />
    <Folder Include="Infrastructure\Data\" />
  </ItemGroup>
</Project>
