// <auto-generated />
using System;
using IrrigacaoInteligente.Core.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IrrigacaoInteligente.Infrastructure.Data.Migrations
{
    [DbContext(typeof(IrrigacaoInteligenteContext))]
    [Migration("20260615133721_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Configuracao", b =>
                {
                    b.Property<string>("Chave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Chave");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("configuracoes", (string)null);
                });

            modelBuilder.Entity("Toolbox.Automacao.Sincronizacao.Data.Entity.ControladorConfiguracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Controlador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("controladores_configuracoes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
