// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using IrrigacaoInteligente.Infrastructure.Data;

#nullable disable

namespace IrrigacaoInteligente.Infrastructure.Data.Migrations
{
    [DbContext(typeof(IrrigacaoInteligenteContext))]
    [Migration("20260410161843_IrrigacaoInteligente.AdicionarDispositivoNaInterface")]
    partial class IrrigacaoInteligenteAdicionarDispositivoNaInterface
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.ConfiguracaoSistema", b =>
                {
                    b.Property<string>("Chave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Chave");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("configuracoes_sistema", (string)null);
                });

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Dispositivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Arquivado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PainelId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("PainelId");

                    b.ToTable("dispositivos", (string)null);
                });

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Interface", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DispositivoConectadoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoBorne")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoLogico")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EnderecoModbus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IndiceModbus")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Marca")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Modelo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModuloConectadoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuloId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Porta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoConectadoId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModuloConectadoId")
                        .IsUnique();

                    b.HasIndex("ModuloId");

                    b.ToTable("interfaces", (string)null);
                });

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Modulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Arquivado")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Controlador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estagio")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Marca")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Master")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Modelo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PainelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("PainelId");

                    b.ToTable("modulos", (string)null);
                });

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Painel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Arquivado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Primario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("paineis", (string)null);
                });

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Porta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DispositivoConectadoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoBorne")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoLogico")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuloId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoConectadoId")
                        .IsUnique();

                    b.HasIndex("EnderecoLogico");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModuloId");

                    b.ToTable("portas", (string)null);
                });

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Dispositivo", b =>
                {
                    b.HasOne("IrrigacaoInteligente.Domain.Entities.Painel", "Painel")
                        .WithMany()
                        .HasForeignKey("PainelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("IrrigacaoInteligente.Domain.Entities.Parametros", "Parametros", b1 =>
                        {
                            b1.Property<Guid>("DispositivoId");

                            b1.Property<double?>("Precisao");

                            b1.Property<double?>("TemperaturaOperacaoMax");

                            b1.Property<double?>("TemperaturaOperacaoMin");

                            b1.Property<double?>("TempoResposta");

                            b1.Property<string>("UnidadeMedida")
                                .IsRequired();

                            b1.Property<double?>("ValorMaximo");

                            b1.Property<double?>("ValorMinimo");

                            b1.HasKey("DispositivoId");

                            b1.ToTable("dispositivos");

                            b1
                                .ToJson("Parametros")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("DispositivoId");
                        });

                    b.Navigation("Painel");

                    b.Navigation("Parametros");
                });

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Interface", b =>
                {
                    b.HasOne("IrrigacaoInteligente.Domain.Entities.Dispositivo", "DispositivoConectado")
                        .WithMany("Interfaces")
                        .HasForeignKey("DispositivoConectadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IrrigacaoInteligente.Domain.Entities.Modulo", "Modulo")
                        .WithMany("Interfaces")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DispositivoConectado");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Modulo", b =>
                {
                    b.HasOne("IrrigacaoInteligente.Domain.Entities.Painel", "Painel")
                        .WithMany("Modulos")
                        .HasForeignKey("PainelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Painel");
                });

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Porta", b =>
                {
                    b.HasOne("IrrigacaoInteligente.Domain.Entities.Dispositivo", "DispositivoConectado")
                        .WithOne("Porta")
                        .HasForeignKey("IrrigacaoInteligente.Domain.Entities.Porta", "DispositivoConectadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IrrigacaoInteligente.Domain.Entities.Modulo", "Modulo")
                        .WithMany("Portas")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DispositivoConectado");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Dispositivo", b =>
                {
                    b.Navigation("Interfaces");

                    b.Navigation("Porta");
                });

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Modulo", b =>
                {
                    b.Navigation("Interfaces");

                    b.Navigation("Portas");
                });

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Painel", b =>
                {
                    b.Navigation("Modulos");
                });
#pragma warning restore 612, 618
        }
    }
}
