// <auto-generated />
using System;
using IrrigacaoInteligente.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IrrigacaoInteligente.Infrastructure.Data.Migrations
{
    [DbContext(typeof(IrrigacaoInteligenteContext))]
    [Migration("20260506114318_Start")]
    partial class Start
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.ConfiguracaoSistema", b =>
                {
                    b.Property<string>("Chave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Chave");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("configuracoes_sistema", (string)null);
                });

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Controlador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuracao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Controladores");
                });
#pragma warning restore 612, 618
        }
    }
}
