// <auto-generated />
using System;
using IrrigacaoInteligente.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IrrigacaoInteligente.Infrastructure.Data.Migrations
{
    [DbContext(typeof(IrrigacaoInteligenteContext))]
    partial class IrrigacaoInteligenteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Configuracao", b =>
                {
                    b.Property<string>("Chave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Chave");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("configuracoes", (string)null);
                });

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Controlador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuracao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("controladores", (string)null);
                });

            modelBuilder.Entity("IrrigacaoInteligente.Domain.Entities.Telemetria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ControladorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dados")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DispositivoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("telemetrias", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
